project_name: nbssh
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
    goarch:
      - amd64

dockers:
- image_templates: ["ghcr.io/goreleaser/example:{{ .Version }}"]
  dockerfile: Dockerfile
  build_flag_templates:
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/Charlie-Root/nbssh
  - --label=org.opencontainers.image.source=https://github.com/Charlie-Root/nbssh
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=MIT
nfpms:
- maintainer: Carlos A Becker <root@carlosbecker.dev>
  description: Sample project.
  homepage: https://github.com/caarlos0/tasktimer
  license: MIT
  formats:
  - deb
  - rpm
  - apk