project_name: nbssh

release:
  prerelease: auto
  draft: true # we only publish after the Windows MSI gets uploaded
  name_template: "GitHub CLI {{.Version}}"

builds:
  - id: macos #build:macos
    goos: [darwin]
    goarch: [amd64, arm64]
    hooks:
      post:
        - cmd: ./script/sign '{{ .Path }}'
          output: true
    binary: bin/gh
    main: ./cmd/gh
    ldflags:
      - -s -w -X github.com/cli/cli/v2/internal/build.Version={{.Version}} -X github.com/cli/cli/v2/internal/build.Date={{time "2006-01-02"}}

  - id: linux #build:linux
    goos: [linux]
    goarch: [386, arm, amd64, arm64]
    env:
      - CGO_ENABLED=0
    binary: bin/gh
    main: ./cmd/gh
    ldflags:
      - -s -w -X github.com/cli/cli/v2/internal/build.Version={{.Version}} -X github.com/cli/cli/v2/internal/build.Date={{time "2006-01-02"}}

  - id: windows #build:windows
    goos: [windows]
    goarch: [386, amd64, arm64]
    hooks:
      post:
        - cmd: >-
            {{ if eq .Runtime.Goos "windows" }}pwsh .\script\sign.ps1{{ else }}./script/sign{{ end }} '{{ .Path }}'
          output: true
    binary: bin/gh
    main: ./cmd/gh
    ldflags:
      - -s -w -X github.com/cli/cli/v2/internal/build.Version={{.Version}} -X github.com/cli/cli/v2/internal/build.Date={{time "2006-01-02"}}

archives:
  - id: linux-archive
    builds: [linux]
    name_template: "gh_{{ .Version }}_linux_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: true
    format: tar.gz
    rlcp: true
    files:
      - LICENSE
      - ./share/man/man1/gh*.1
  - id: macos-archive
    builds: [macos]
    name_template: "gh_{{ .Version }}_macOS_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: true
    format: zip
    rlcp: true
    files:
      - LICENSE
      - ./share/man/man1/gh*.1
  - id: windows-archive
    builds: [windows]
    name_template: "gh_{{ .Version }}_windows_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: false
    format: zip
    rlcp: true
    files:
      - LICENSE

